In [19]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score, recall_score
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.callbacks import EarlyStopping

In [20]:
df = pd.read_csv('Churn_treino.csv', sep=';')
df.head()

CreditScore Geography  Gender  Age  Tenure   Balance  NumOfProducts  \
0          619    France  Female   42       2         0              1   
1          608     Spain  Female   41       1   8380786              1   
2          502    France  Female   42       8   1596608              3   
3          699    France  Female   39       1         0              2   
4          850     Spain  Female   43       2  12551082              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1         10134888       1  
1          0               1         11254258       0  
2          1               0         11393157       1  
3          0               0          9382663       0  
4          1               1           790841       0

In [21]:
X = df.drop('Exited', axis=1)
y = df['Exited']

In [22]:
standarscaler = StandardScaler()
numerical = X.select_dtypes(include=['int64', 'float64']).columns
# Use the instance of StandardScaler (standardscaler) to call fit_transform
X[numerical] = standarscaler.fit_transform(X[numerical])

In [23]:
X

CreditScore Geography  Gender       Age    Tenure   Balance  \
0       -0.326221    France  Female  0.293517 -1.041760 -1.110553   
1       -0.440036     Spain  Female  0.198164 -1.387538  0.222782   
2       -1.536794    France  Female  0.293517  1.032908 -0.856542   
3        0.501521    France  Female  0.007457 -1.387538 -1.110553   
4        2.063884     Spain  Female  0.388871 -1.041760  0.886252   
...           ...       ...     ...       ...       ...       ...   
9995     1.246488    France    Male  0.007457 -0.004426 -1.110553   
9996    -1.391939    France    Male -0.373958  1.724464 -0.197835   
9997     0.604988    France  Female -0.278604  0.687130 -1.110553   
9998     1.256835   Germany    Male  0.293517 -0.695982  0.083852   
9999     1.463771    France  Female -1.041433 -0.350204  0.959944   

      NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  
0         -0.911583   0.646092        0.970243         0.170614  
1         -0.911583  -1.547768        0.970243         0.353281  
2          2.527057   0.646092       -1.030670         0.375948  
3          0.807737  -1.547768       -1.030670         0.047859  
4         -0.911583   0.646092        0.970243        -1.354223  
...             ...        ...             ...              ...  
9995       0.807737   0.646092       -1.030670         0.087743  
9996      -0.911583   0.646092        0.970243         0.176340  
9997      -0.911583  -1.547768        0.970243        -0.796492  
9998       0.807737   0.646092       -1.030670         0.032551  
9999      -0.911583   0.646092       -1.030670        -0.860051  

[10000 rows x 10 columns]

In [24]:
labelencoder = LabelEncoder()
categorical = X.select_dtypes(include='object').columns
# Use the instance of LabelEncoder (labelencoder) to call fit_transform
for col in categorical:
    X[col] = labelencoder.fit_transform(X[col])

In [25]:
X

CreditScore  Geography  Gender       Age    Tenure   Balance  \
0       -0.326221          0       0  0.293517 -1.041760 -1.110553   
1       -0.440036          2       0  0.198164 -1.387538  0.222782   
2       -1.536794          0       0  0.293517  1.032908 -0.856542   
3        0.501521          0       0  0.007457 -1.387538 -1.110553   
4        2.063884          2       0  0.388871 -1.041760  0.886252   
...           ...        ...     ...       ...       ...       ...   
9995     1.246488          0       1  0.007457 -0.004426 -1.110553   
9996    -1.391939          0       1 -0.373958  1.724464 -0.197835   
9997     0.604988          0       0 -0.278604  0.687130 -1.110553   
9998     1.256835          1       1  0.293517 -0.695982  0.083852   
9999     1.463771          0       0 -1.041433 -0.350204  0.959944   

      NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  
0         -0.911583   0.646092        0.970243         0.170614  
1         -0.911583  -1.547768        0.970243         0.353281  
2          2.527057   0.646092       -1.030670         0.375948  
3          0.807737  -1.547768       -1.030670         0.047859  
4         -0.911583   0.646092        0.970243        -1.354223  
...             ...        ...             ...              ...  
9995       0.807737   0.646092       -1.030670         0.087743  
9996      -0.911583   0.646092        0.970243         0.176340  
9997      -0.911583  -1.547768        0.970243        -0.796492  
9998       0.807737   0.646092       -1.030670         0.032551  
9999      -0.911583   0.646092       -1.030670        -0.860051  

[10000 rows x 10 columns]

In [26]:
X_treino, X_teste, y_treino, y_teste = train_test_split(X, y, test_size=0.3, random_state=0)

In [28]:
modelo = Sequential()
modelo.add(Dense(units=64, activation='relu', input_dim=X_treino.shape[1]))
modelo.add(Dropout(0.4))
modelo.add(Dense(units=32, activation='relu'))
modelo.add(Dropout(0.4))
modelo.add(Dense(units=32, activation='relu'))
modelo.add(Dropout(0.4))
modelo.add(Dense(units=1, activation='sigmoid'))

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [29]:
modelo.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
modelo.fit(X_treino, y_treino, epochs=50, batch_size=32)

Epoch 1/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7830 - loss: 0.5354
Epoch 2/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7961 - loss: 0.4712
Epoch 3/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8005 - loss: 0.4477
Epoch 4/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7973 - loss: 0.4599
Epoch 5/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8057 - loss: 0.4340
Epoch 6/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8060 - loss: 0.4425
Epoch 7/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8100 - loss: 0.4236
Epoch 8/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8133 - loss: 0.4247
Epoch 9/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8302 - loss: 0.4046
Epoch 10/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8285 - loss: 0.4019
Epoch 11/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8356 - loss: 0.3870
Epoch 12/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

In [30]:
previsoes = modelo.predict(X_teste)
previsoes

94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step


array([[0.28940725],
       [0.25675434],
       [0.22472584],
       ...,
       [0.06371167],
       [0.09874269],
       [0.6493693 ]], dtype=float32)

In [32]:
y_pred = (previsoes > 0.5).astype('int32')
y_pred

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [1]], dtype=int32)

In [35]:
print('Acurácia: ', accuracy_score(y_teste, y_pred))
print('F1 Score: ', f1_score(y_teste, y_pred))
print('Recall: ', recall_score(y_teste, y_pred))
print('Matriz de confusão: \n', confusion_matrix(y_teste, y_pred))

Acurácia:  0.8623333333333333
F1 Score:  0.5954946131243879
Recall:  0.4895330112721417
Matriz de confusão: 
 [[2283   96]
 [ 317  304]]
